version: "3"


services:

  # AI server
  AI_backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: trinhvideo123/pbl6-attendance-sp:v2-celery
    ports:
      - "8888:8888"
    environment:
      - WORKER_CLASS=uvicorn.workers.UvicornWorker
      - PORT=8888
      - ENV=DEPLOY
    restart: always
    networks:
      AI_WORKER_BACKEND:
        aliases:
          - AI_BACKEND

  # celery worker
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: trinhvideo123/pbl6-attendance-sp:v2-celery
    command: celery -A celery_task.worker worker -l info -c 1 -O fair --without-gossip --without-mingle --without-heartbeat
    environment:
      - OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
      #      - BE_SERVER=http://illusion.codes:9999/api/records
      - BE_SERVER=http://DATA_BACKEND:8080/api/records
    deploy:
      replicas: 2
    volumes:
      - /home/pbl6/images:/app/upload
      - /home/pbl6/models:/app/resources
    restart: always
    networks:
      AI_WORKER_BACKEND:
        aliases:
          - WORKER

  # backend server
  backend:
    image: trinhvideo123/pbl6-backend:node
    ports:
      - "9999:8080"
    restart: unless-stopped
    networks:
      AI_WORKER_BACKEND:
        aliases:
          - DATA_BACKEND


networks:
  AI_WORKER_BACKEND: