version: "3"


services:

  # AI server
  AI_backend:
    image: trinhvideo123/pbl6-attendance-sp:v3
    environment:
      - PORT=8888
      - ENV=DEPLOY
      - WORKER_CLASS=uvicorn.workers.UvicornWorker
      - MAX_REQUEST_SIZE=6291456
    ports:
      - "127.0.0.1:8888:8888"
    restart: unless-stopped
    healthcheck:
      test: curl localhost:8888/api/health
      interval: 60s
      timeout: 3s
      retries: 3
    networks:
      AI_WORKER_BACKEND:
        aliases:
          - AI_BACKEND

  # celery worker
  worker:
    image: trinhvideo123/pbl6-attendance-sp:v3
    command: celery -A celery_task.worker worker -l info -c 1 --max-tasks-per-child 100 -O fair --without-gossip --without-mingle --without-heartbeat
    deploy:
      replicas: 1
    environment:
      - BROKER_URI=redis://redis/
      - BACKEND_URI=redis://redis/
      - RESULT_EXPIRE=300
      - OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
      - FACE_THRESH=0.55
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      AI_WORKER_BACKEND:
        aliases:
          - WORKER

  # redis as message broker
  redis:
    image: redis:alpine
    networks:
      AI_WORKER_BACKEND:
        aliases:
          - REDIS


  # backend server
  backend:
    image: trinhvideo123/pbl6-attendance-sp:backend
    ports:
      - "127.0.0.1:9999:8080"
    restart: unless-stopped
    networks:
      AI_WORKER_BACKEND:
        aliases:
          - DATA_BACKEND


networks:
  AI_WORKER_BACKEND: