version: "3"


services:

  # AI server
  AI_backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: trinhvideo123/pbl6-attendance-sp:v2
    ports:
      - "127.0.0.1:8888:8888"
    restart: always
    networks:
      AI_WORKER_BACKEND:
        aliases:
          - AI_BACKEND

  # celery worker
  worker:
    image: trinhvideo123/pbl6-attendance-sp:v2
    command: celery -A celery_task.worker worker -l info -c 1 --max-tasks-per-child 100 --max-memory-per-child 1000000 -O fair --without-gossip --without-mingle --without-heartbeat
    deploy:
      replicas: 1
    volumes:
      - /home/pbl6/images:/app/upload
      - /home/pbl6/models:/app/resources
    restart: always
    networks:
      AI_WORKER_BACKEND:
        aliases:
          - WORKER

  # backend server
  backend:
    image: trinhvideo123/pbl6-attendance-sp:backend
    ports:
      - "127.0.0.1:9999:8080"
    restart: unless-stopped
    networks:
      AI_WORKER_BACKEND:
        aliases:
          - DATA_BACKEND


networks:
  AI_WORKER_BACKEND: